/*

 BLACK_SQUARE_SPRITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __black_square_sprite_h_INCLUDE
#define __black_square_sprite_h_INCLUDE

/* Bank of tiles. */
#define black_square_spriteBank 0
/* Start of tile array. */
extern const unsigned char black_square_sprite[];

#endif

/* End of BLACK_SQUARE_SPRITE.H */
