/*

 D01_ROOM_01_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 128 x 128
   Tile set      : D01_Sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __D01_Room_01_Map_h_INCLUDE
#define __D01_Room_01_Map_h_INCLUDE

#define D01_Room_01_MapWidth 128
#define D01_Room_01_MapHeight 128
#define D01_Room_01_MapBank 0

extern const unsigned char D01_Room_01_Map[];

#endif

/* End of D01_ROOM_01_MAP.H */
