/*

 D01_ROOM_01_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 59

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __D01_Room_01_Sprites_h_INCLUDE
#define __D01_Room_01_Sprites_h_INCLUDE

/* Bank of tiles. */
#define D01_Room_01_SpritesBank 0
/* Start of tile array. */
extern const unsigned char D01_Room_01_Sprites[];

#endif

/* End of D01_ROOM_01_SPRITES.H */
