/*

 E01_ROOM_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 23 x 23
   Tile set      : Entry.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __E01_Room_Map_h_INCLUDE
#define __E01_Room_Map_h_INCLUDE

#define E01_Room_MapWidth 23
#define E01_Room_MapHeight 23
#define E01_Room_MapBank 0

extern const unsigned char E01_Room_Map[];

#endif

/* End of E01_ROOM_MAP.H */
