/*

 E01_ROOM_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 10

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __E01_Room_Sprites_h_INCLUDE
#define __E01_Room_Sprites_h_INCLUDE

/* Bank of tiles. */
#define E01_Room_SpritesBank 0
/* Start of tile array. */
extern const unsigned char E01_Room_Sprites[];

#endif

/* End of E01_ROOM_SPRITES.H */
