#ifndef __INCLUDE_LUT_HEADER
#define __INCLUDE_LUT_HEADER

// !! This code has been generated by the LUT tools, don't update it by hand !! 
#define SINE_LUT_COUNT 256
extern const signed char sine_lut[];

#endif