/*

 LIFE_SPRITE.C

 Tile Source File.

 Info:
	Form                 : All tiles as one unit.
	Format               : Gameboy 4 color.
	Compression          : None.
	Counter              : None.
	Tile size            : 8 x 8
	Tiles                : 0 to 0

	Palette colors       : None.
	SGB Palette          : None.
	CGB Palette          : None.

	Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char life_sprite[] =
{
		0x3C, 0x3C, 0x24, 0x3C, 0xF7, 0xEF, 0x99, 0xE7,
		0xBD, 0xC3, 0xF7, 0xEF, 0x24, 0x3C, 0x3C, 0x3C,
};

/* End of LIFE_SPRITE.C */
