/*

 UI_DIALOG_BORDERS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __ui_dialog_borders_h_INCLUDE
#define __ui_dialog_borders_h_INCLUDE

/* Bank of tiles. */
#define ui_dialog_bordersBank 0
#define ui_dialog_sprites_count 8
/* Start of tile array. */
extern const unsigned char ui_dialog_borders[];

#endif

/* End of UI_DIALOG_BORDERS.H */
