#include "lut_generator.h"

const char *gen_lut_sine_cmd = "gsl";
const __int8 lut_flag_remap = 3;
const __int8 lut_flag_step = 4;
const __int8 lut_flag_file_path = 5;

static const char *output_folder = "../res";
static const char *output_flag_name = "-output";
static const char *step_flag_name = "-step";
static const char *remap_flag_name = "-remap";

const char *try_get_flag_v(const char *argv[], u8 len, const char *flag_name)
{
    for (u8 i = 2; i < len; i++)
    {
        const char *flag = argv[i];
        if (flag == NULL)
        {
            break;
        }

        if (strcmp(flag_name, flag) == 0 && (i + 1) < len)
        {
            u8 next = i + 1;
            const char *flagv = argv[next];
            if (flagv != NULL)
            {
                return flagv;
            }
        }
    }

    return NULL;
}

int main(int argsc, const char *argv[])
{
    if (argsc <= 1)
    {
        printf("[Early exit] no commands provided");
        return 0;
    }

    const char *output_flag_v = try_get_flag_v(argv, argsc, output_flag_name);
    if (output_flag_v != NULL)
    {
        printf("[Generate] output folder is now: %s\n", output_flag_v);
        output_folder = output_flag_v;
    }

    const char *cmd = argv[1];

    if (strcmp(cmd, gen_lut_sine_cmd) == 0)
    {
        i16 remap_val = 127;
        double step = 1.40625; // remapping for 8 bit numbers (360deg/256)
        char *end;

        const char *remap_flag_v = try_get_flag_v(argv, argsc, remap_flag_name);
        if (remap_flag_v != NULL)
        {
            printf("[Generate] remap value is now: [%s; %s]\n", remap_flag_v, remap_flag_v);
            remap_val = strtol(remap_flag_v, &end, 10);
        }

        const char *step_falg_v = try_get_flag_v(argv, argsc, step_flag_name);
        if (step_falg_v != NULL)
        {
            printf("[Generate] step in degrees: %s\n", step_falg_v);
            step = strtof(step_falg_v, &end);
        }

        gen_sine_lut(remap_val, step);
    }

    return 0;
}

u8 write_lut_header(FILE *file, void *data)
{
    [[maybe_unused]] void *_data = data;

    const char *header =
        "#ifndef __INCLUDE_LUT_HEADER\n"
        "#define __INCLUDE_LUT_HEADER\n\n"
        "// !! This code has been generated by the LUT tools, don't update it by hand !! \n"
        "#define SINE_LUT_COUNT 256\n"
        "extern const signed char sine_lut[];\n\n"
        "#endif";

    fputs(header, file);

    return 0;
}

u8 write_lut_source(FILE *file, void *data)
{
    LutSourceData *source_data = (LutSourceData *)data;

    fputs(source_data->additional_content, file);

    char *header = "const signed char sine_lut[] = {\n";
    fputs(header, file);

    for (int i = 0; i < 256; i++)
    {
        char str[8];
        const char *iterp = i < 255 ? "%i," : "%i";

        sprintf(str, iterp, source_data->sine_wave[i]);
        fputs(str, file);
    }

    char *footer = "\n};\n";
    fputs(footer, file);

    return 0;
}

void gen_sine_lut(i16 remap_value, double deg_step)
{
    printf("[Generate] sine wave look up table %i, %f \n", remap_value, deg_step);

    const float deg2rad = (PI / 180.0);
    double deg = deg_step;
    double acc = 0;
    i8 sine_lut[256];
    for (int i = 0; i < 256; i++)
    {
        const double c = sin(acc * deg2rad);
        const i16 r = (i16)((double)remap_value * c);

        sine_lut[i] = r;
        acc += deg;
    }

    char file_path_source[255];
    strcpy(file_path_source, output_folder);
    strcat(file_path_source, "/gen_sine_lut.c");
    printf("[Generate] file source will be written at %s\n", file_path_source);

    char file_path_header[255];
    strcpy(file_path_header, output_folder);
    strcat(file_path_header, "/gen_sine_lut.h");
    printf("[Generate] file header will be written at %s\n", file_path_header);

    // HEADER WRITE
    FileWriteCallback header_cb = {.callback = write_lut_header, .data = NULL};
    write(file_path_header, header_cb);

    // SOURCE WRITE
    LutSourceData source_data = {.sine_wave = &sine_lut[0], .additional_content = "#include \"gen_sine_lut.h\"\n\n"};
    FileWriteCallback source_cb = {.callback = write_lut_source, .data = (void *)&source_data};
    write(file_path_source, source_cb);
}

void write(const char *file_path, FileWriteCallback callback)
{
    FILE *file;
    file = fopen(file_path, "w");

    if (file == NULL)
    {
        printf(ANSI_COLOR_RED "[Error Generate] failed to create file for sine wave look up table, make sure the path exist" ANSI_COLOR_RESET);
        return;
    }

    u8 k = (callback.callback)(file, callback.data);
    while (k > 0)
    {
        k = (callback.callback)(file, callback.data);
    }

    fflush(file);
    fclose(file);
}
