/*

 TILES_MAP_01.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 12

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tiles_map_01_h_INCLUDE
#define __tiles_map_01_h_INCLUDE

/* Bank of tiles. */
#define tiles_map_01Bank 0
/* Start of tile array. */
extern const unsigned char tiles_map_01[];

#endif

/* End of TILES_MAP_01.H */
